project:
  type: website
  output-dir: docs

website:
  title: "Stanley Lo"
  navbar:
    left:
      - href: index.qmd
        text: Home
        menu:
        - text: "About"
          href: about.html
        - text: "Plots Project 1"
          href: plots-project1.html
        - text: "Friends Character Data"
          href: Friends-Character-Data.html
        - text: "Simulation" 
          href: Simulation.html
        - text: "EthicsDataPower" 
          href: EthicsDataPower.html

# ~ additional metadata excluded for brevity ~

# supplying a light ("minty") and dark ("slate") theme to toggle between
format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    page-layout: full