project:
  type: website
  output-dir: docs

website:
  title: "Stanley Lo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Plots-Project1.qmd
      - Friends-Character-Data.qmd
      - Simulation.qmd

# ~ additional metadata excluded for brevity ~

# supplying a light ("minty") and dark ("slate") theme to toggle between
format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    page-layout: full